# Generated by Django 4.0.1 on 2022-01-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_arrayjsonmodel_jsonmodel_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='ingredients',
        ),
    ]
