# Generated by Django 4.0.1 on 2022-01-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_cocktail_ingredients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArrayJSONModel',
        ),
        migrations.DeleteModel(
            name='JSONModel',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
