# Generated by Django 4.0.1 on 2022-01-10 19:06

from django.db import migrations
import jsoneditor.fields.django3_jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_arrayjsonmodel_delete_jsonmodel_delete_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='ingredients',
            field=jsoneditor.fields.django3_jsonfield.JSONField(),
        ),
    ]
